[package]
edition = "2021"
name = "contract-import-dependency-remediated-1"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
dependency-contract = { path = "../dependency-contract" }
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]
