[workspace]
exclude = [".cargo", ".vscode", "target"]
members = ["*"]
resolver = "2"

[workspace.dependencies]
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "feb18ca1ee3c195e9127d6acf20da99159fca581", package = "clippy_utils" }
common = { path = "../../common" }
common_detectors = { path = "../../common/detectors", package = "common-detectors" }
common_utils = { path = "../../common/utils", package = "common-utils" }
dylint_internal = "=3.1.2"
dylint_linting = "=3.1.2"
if_chain = "=1.0.2"
itertools = { version = "=0.13" }
