[package]
edition = "2021"
name = "missing-new-admin-auth"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
clippy_utils = { workspace = true }
common = { workspace = true }
dylint_internal = { workspace = true }
dylint_linting = { workspace = true }
edit-distance = "=2.1.2"
if_chain = { workspace = true }

[package.metadata.rust-analyzer]
rustc_private = true
