[package]
edition = "2024"
name = "vec-could-be-mapping"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
clippy_utils = { workspace = true }
common = { workspace = true }
dylint_internal = { workspace = true }
dylint_linting = { workspace = true }
if_chain = { workspace = true }
itertools = { workspace = true }

[package.metadata.rust-analyzer]
rustc_private = true
