[package]
edition = "2021"
name = "analysis"
version = "0.1.0"

[dependencies]
if_chain = "=1.0.2"
clippy_utils = "=0.1.90"
paste = "1.0"
dylint_linting = "=3.1.2"

[package.metadata.rust-analyzer]
rustc_private = true
