[package]
edition = "2021"
name = "common-detectors"
version = "0.1.0"

[dependencies]
analysis = { path = "../analysis" }
clippy_utils = "=0.1.90"
dylint_internal = "=3.1.2"
dylint_linting = "=3.1.2"
if_chain = "=1.0.2"

[package.metadata.rust-analyzer]
rustc_private = true
